### ISSUE TITLE
Idea: Loot tab

### ISSUE THREAD

**Issue by NukeMaster0** [rinnocenti/innocenti-looting#1]
Instead of items that the players aren't meant to receive perhaps a looting tab could be a good idea, kinda like a mod in Minecraft called "Custom NPC" where it has a chance to drop THOSE items instead of what the NPC is carrying/wielding:

Ex:
![image](https://user-images.githubusercontent.com/68701755/103487540-3f93fa00-4dd4-11eb-88bb-31be3878e854.png)

Thank you!

**Comment by rinnocenti** [comment]
The idea of the module is to provide an option for the D&D system (and Rpg in general) and as such it has its own system of random rewards.
At first the module is operating only with items placed in the inventory.
But in D&D there is random looting where tables are created to provide the types of items that each NPC group can "drop".
So having to configure a plan for each NPC would not be viable and is not supported by the system.

The idea of percentages of items that are not looting, comes from the rule of the game where in combat items can be damage or break and cannot be used.

Soon I will launch an update where GM will be able to create his own loot list, but for now only the items that are in his inventory.

**Comment by NukeMaster0** [comment]
> The idea of the module is to provide an option for the D&D system (and Rpg in general) and as such it has its own system of random rewards.
> At first the module is operating only with items placed in the inventory.
> But in D&D there is random looting where tables are created to provide the types of items that each NPC group can "drop".
> So having to configure a plan for each NPC would not be viable and is not supported by the system.
> 
> The idea of percentages of items that are not looting, comes from the rule of the game where in combat items can be damage or break and cannot be used.
> 
> Soon I will launch an update where GM will be able to create his own loot list, but for now only the items that are in his inventory.

Thank you!
